services:
  auth-service:
    build: 
      context: ./apps/auth_service
      dockerfile: local.Dockerfile
    volumes:
      - ./apps/auth_service:/app  
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - mysql
    environment:
      - PYTHONDONTWRITEBYTECODE=1
  

  # post-service:
  #   build: ./services/post-service
  #   ports:
  #     - 3001:3000
  #   env_file:
  #     - .env.dev
  #   depends_on:
  #     - mongodb

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - .env.dev

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports: 
     - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql 

  # mongodb:
  #   image: mongo

volumes:
  mysql_data:  
