definitions:
  handlers.EmotionCreateRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  handlers.EmotionNameUpdateRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  handlers.ErrorResponse:
    properties:
      error:
        example: 不正な入力です
        type: string
    type: object
  handlers.PostEmotionUpdateRequest:
    properties:
      emotion_id:
        type: integer
      intensity:
        type: integer
    required:
    - emotion_id
    - intensity
    type: object
  handlers.SuccessResponse:
    properties:
      message:
        example: 操作が成功しました
        type: string
    type: object
  models.Emotion:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      isPreset:
        type: boolean
      name:
        type: string
      posts:
        items:
          $ref: '#/definitions/models.PostEmotion'
        type: array
    type: object
  models.Post:
    properties:
      createdAt:
        type: string
      emotions:
        items:
          $ref: '#/definitions/models.PostEmotion'
        type: array
      id:
        type: integer
    type: object
  models.PostEmotion:
    properties:
      custom:
        type: string
      emotion:
        $ref: '#/definitions/models.Emotion'
      emotionID:
        type: integer
      intensity:
        type: integer
      post:
        $ref: '#/definitions/models.Post'
      postID:
        type: integer
      userID:
        type: integer
    type: object
info:
  contact: {}
paths:
  /emotions:
    get:
      description: すべての登録感情を取得
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Emotion'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: 感情一覧を取得
      tags:
      - emotions
    post:
      consumes:
      - application/json
      description: ユーザー定義の感情を登録する（重複不可）
      parameters:
      - description: 感情登録リクエスト
        in: body
        name: emotion
        required: true
        schema:
          $ref: '#/definitions/handlers.EmotionCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Emotion'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: 感情を新規登録する
      tags:
      - emotions
  /emotions/{id}:
    delete:
      description: 投稿で使用されていない感情を削除する
      parameters:
      - description: 感情ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SuccessResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: 感情をIDで削除
      tags:
      - emotions
    put:
      consumes:
      - application/json
      description: 感情の名前を変更する
      parameters:
      - description: 感情ID
        in: path
        name: id
        required: true
        type: string
      - description: 感情名更新内容
        in: body
        name: emotion
        required: true
        schema:
          $ref: '#/definitions/handlers.EmotionNameUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Emotion'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: 感情名の更新
      tags:
      - emotions
  /emotions/unused:
    get:
      description: 投稿に紐づいていない感情のみを返す
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Emotion'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: 未使用感情一覧を取得
      tags:
      - emotions
  /post-emotions/{post_id}/{user_id}:
    delete:
      description: 指定された投稿ID・ユーザーIDに紐づく感情を削除、Redisキャッシュも削除
      parameters:
      - description: 投稿ID
        in: path
        name: post_id
        required: true
        type: string
      - description: ユーザーID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SuccessResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: 投稿に紐づく感情を削除
      tags:
      - post-emotions
    get:
      description: 投稿ID・ユーザーIDに紐づく感情をRedisまたはDBから取得
      parameters:
      - description: 投稿ID
        in: path
        name: post_id
        required: true
        type: string
      - description: ユーザーID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PostEmotion'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: 投稿に紐づく感情を取得
      tags:
      - post-emotions
    put:
      consumes:
      - application/json
      description: 投稿ID・ユーザーIDを指定して感情を更新、キャッシュも更新
      parameters:
      - description: 投稿ID
        in: path
        name: post_id
        required: true
        type: string
      - description: ユーザーID
        in: path
        name: user_id
        required: true
        type: string
      - description: 感情更新内容
        in: body
        name: emotion
        required: true
        schema:
          $ref: '#/definitions/handlers.PostEmotionUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PostEmotion'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: 投稿に紐づく感情を更新
      tags:
      - post-emotions
swagger: "2.0"
